// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                          103
// Async Callback (empty):               1
// Total number of exported functions: 106

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    controller
    (
        init => init
        upgrade => upgrade
        getAdmin => get_admin
        getPendingAdmin => get_pending_admin
        setPendingAdmin => set_pending_admin
        acceptAdmin => accept_admin
        supportMarket => support_market
        setMaxMarketsPerAccount => set_max_markets_per_account
        setCollateralFactors => set_collateral_factors
        setPriceOracle => set_price_oracle
        setLiquidityCap => set_liquidity_cap
        setBorrowCap => set_borrow_cap
        setMaxRewardsBatches => set_max_rewards_batches
        setMaxSlippage => set_max_slippage
        setRewardsBatch => set_rewards_batch
        addRewardsBatch => add_rewards_batch
        cancelRewardsBatch => cancel_rewards_batch
        removeRewardsBatch => remove_rewards_batch
        adminRemoveRewardsBatch => admin_remove_rewards_batch
        updateRewardsBatchSpeed => update_rewards_batch_speed
        updateRewardsBatchRemainingPeriod => update_rewards_batch_remaining_period
        claimUndistributedRewards => claim_undistributed_rewards
        supportRewardsBatchBoosting => support_rewards_batch_boosting
        enableRewardsBatchBoosting => enable_rewards_batch_boosting
        disableRewardsBatchBoosting => disable_rewards_batch_boosting
        boostRewards => boost_rewards
        updateBooster => update_booster
        cancelBooster => cancel_booster
        setAccountTokens => set_account_collateral_tokens
        setRewardsManager => set_rewards_manager
        setPauseGuardian => set_pause_guardian
        setBoosterObserver => set_booster_observer
        clearBoosterObserver => clear_booster_observer
        setUshMarketObserver => set_ush_market_observer
        clearUshMarketObserver => clear_ush_market_observer
        pauseMint => pause_mint
        pauseBorrow => pause_borrow
        pauseSeize => pause_seize
        pauseGlobalSeize => pause_global_seize
        enterMarkets => enter_markets
        exitMarket => exit_market
        exitMarketAndRedeem => exit_market_and_redeem
        removeAccountMarket => remove_account_market
        mintAllowed => mint_allowed
        redeemAllowed => redeem_allowed
        borrowAllowed => borrow_allowed
        repayBorrowAllowed => repay_borrow_allowed
        liquidateBorrowAllowed => liquidate_borrow_allowed
        seizeAllowed => seize_allowed
        updateRewardsBatchesState => update_rewards_batches_state
        distributeRewards => distribute_rewards
        claimRewards => claim_rewards
        claimRewardsTokens => claim_rewards_tokens
        isRisky => is_risky
        simulateRiskProfile => simulate_risk_profile
        isController => is_controller
        isWhitelistedMoneyMarket => is_whitelisted_money_market
        isWhitelistedTokenId => is_whitelisted_token_id
        isBoosterObserver => is_booster_observer
        isUshMarketObserver => is_ush_market_observer
        isDeprecated => is_deprecated
        getWhitelistedMarkets => get_whitelisted_markets
        getAccountMarkets => get_account_markets
        getMaxCollateralFactor => get_max_collateral_factor
        getAccountTokens => get_account_collateral_tokens
        getTotalCollateralTokens => get_total_collateral_tokens
        updateAndGetCollateralFactor => update_and_get_collateral_factor
        updateAndGetUshBorrowerCollateralFactor => update_and_get_ush_borrower_collateral_factor
        updateAndGetCollateralFactors => update_and_get_collateral_factors
        getMintStatus => get_mint_status
        getBorrowStatus => get_borrow_status
        getSeizeStatus => get_seize_status
        getGlobalSeizeStatus => get_global_seize_status
        getAccountAccruedRewards => get_account_accrued_rewards
        burnTokens => burn_tokens
        transferTokens => transfer_tokens
        tokensToSeize => tokens_to_seize
        getPauseGuardian => pause_guardian
        getRewardsManager => rewards_manager
        getMoneyMarketByTokenId => money_markets
        getIdentifiersByMoneyMarket => identifiers
        getMarketMembers => market_members
        getMaxMarketsPerAccount => max_markets_per_account
        getPriceOracle => price_oracle
        getCollateralFactor => collateral_factor
        getUshBorrowerCollateralFactor => ush_borrower_collateral_factor
        getNextCollateralFactor => next_collateral_factors
        getLiquidityCap => liquidity_cap
        getBorrowCap => borrow_cap
        getAccountRewardsIndex => account_batch_rewards_index
        getNextRewardsBatchId => next_rewards_batch_id
        getMaxRewardsBatchesPerMarket => max_rewards_batches
        getMaxSlippage => max_slippage
        getRewardsBatches => rewards_batches
        getUndistributedRewards => undistributed_rewards
        getRewardsBatchPosition => rewards_batch_position
        getRewardsBooster => rewards_booster
        getEgldWrapper => egld_wrapper
        getWegldId => wegld_id
        getGovernanceTokenId => governance_token_id
        getRouter => router
        getBoostingState => boosting_state
        isRewardsBatchBoostingSupported => rewards_batch_boosting_supported
        getBoosterObserver => booster_observer
        getUshMarketObserver => ush_market_observer
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
