[package]
name = "discount-rate-model-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.discount-rate-model]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.53.0"
