// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           40
// Async Callback (empty):               1
// Total number of exported functions:  43

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    oracle
    (
        init => init
        upgrade => upgrade
        getAdmin => get_admin
        getPendingAdmin => get_pending_admin
        setPendingAdmin => set_pending_admin
        acceptAdmin => accept_admin
        isPriceOracle => is_price_oracle
        setGuardian => set_guardian
        unpauseToken => unpause_token
        pauseToken => pause_token
        supportPriceAggregator => support_price_aggregator
        updateRoundDuration => update_round_duration
        supportNativeToken => support_native_token
        supportEgldLsToken => support_egld_ls_token
        supportTaoLsToken => support_tao_ls_token
        supportUshToken => support_ush_token
        setUshFallbackToken => set_ush_fallback_token
        setPricingMethod => set_pricing_method
        setAnchorTolerances => set_anchor_tolerances
        getPrice => get_price_in_egld
        getXExchangeInstantaneousPriceInEgld => get_xexchange_instantaneous_price_in_egld
        getXExchangeSafePriceInEgld => get_xexchange_safe_price_in_egld
        getPriceAggregatorPriceInEgld => get_price_aggregator_price_in_egld
        getEgldWrapper => egld_wrapper
        getWegldId => wegld_id
        getLiquidStakingAddress => liquid_staking
        getTaoLiquidStakingAddress => tao_liquid_staking
        getUshMinter => ush_minter
        getLsTokenId => ls_token_id
        getStaoTokenId => stao_token_id
        getUshTokenId => ush_token_id
        getUshFallbackTokenId => ush_fallback_token_id
        getXExchangePricingMethod => xexchange_pricing_method
        getGuardian => guardian
        getPriceAggregatorAddress => price_aggregator_address
        getRoundDuration => round_duration
        getWhitelistedTokens => whitelisted_tokens
        getSupportedTokens => supported_tokens
        getPricingMethod => pricing_method
        getLastPrice => last_price
        hasUnreliablePrice => has_unreliable_price
        isPaused => is_token_paused
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
