// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           80
// Async Callback:                       1
// Total number of exported functions:  83

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    money_market
    (
        init => init
        upgrade => upgrade
        issueEsdtToken => issue_esdt_token
        setMarketRoles => set_market_roles
        mintInitialSupply => mint_initial_supply
        getAdmin => get_admin
        getPendingAdmin => get_pending_admin
        setPendingAdmin => set_pending_admin
        acceptAdmin => accept_admin
        borrow => borrow
        isMoneyMarket => is_money_market
        isTokenIssued => is_token_issued
        accrueInterest => accrue_interest
        tryAccrueInterest => try_accrue_interest
        addReserves => add_reserves
        underlyingAmountToTokens => underlying_amount_to_tokens
        tokensToUnderlyingAmount => tokens_to_underlying_amount
        currentUnderlyingAmountToTokens => current_underlying_amount_to_tokens
        currentTokensToUnderlyingAmount => current_tokens_to_underlying_amount
        getMoneyMarketIdentifiers => get_money_market_identifiers
        getCurrentTotalBorrows => current_total_borrows
        getBaseTotalBorrows => get_base_total_borrows
        getCurrentTotalReserves => current_total_reserves
        getCurrentStakingRewards => get_current_staking_rewards
        getCurrentHistoricalStakingRewards => get_current_historical_staking_rewards
        getCurrentRevenue => get_current_revenue
        getCurrentLiquidity => get_current_liquidity
        getLiquidity => get_liquidity
        getReserveFactor => get_reserve_factor
        getInterestRateModel => get_interest_rate_model
        getController => get_controller
        getStakingContract => get_staking_contract
        getCurrentAccountBorrowAmount => current_account_borrow_amount
        getReliableAccountBorrowAmount => reliable_account_borrow_amount
        getStoredAccountBorrowAmount => stored_account_borrow_amount
        getBaseAccountBorrowAmount => base_account_borrow_amount
        getAccountSnapshot => get_account_snapshot
        getReliableAccountSnapshot => get_reliable_account_snapshot
        getBorrowIndex => get_borrow_index
        getCurrentExchangeRate => get_current_exchange_rate
        getStoredExchangeRate => get_stored_exchange_rate
        getBorrowRatePerSecond => borrow_rate_per_second
        getSupplyRatePerSecond => supply_rate_per_second
        getRatesPerSecond => get_rates_per_second
        getCloseFactor => get_close_factor
        getLiquidationIncentive => get_liquidation_incentive
        setStakingContract => set_staking_contract
        setReserveFactor => set_reserve_factor
        setStakeFactor => set_stake_factor
        setCloseFactor => set_close_factor
        setLiquidationIncentive => set_liquidation_incentive
        setProtocolSeizeShare => set_protocol_seize_share
        setInterestRateModel => set_interest_rate_model
        reduceReserves => reduce_reserves
        setAccrualTimeThreshold => set_accrual_time_threshold
        addTrustedMinter => add_trusted_minter
        removeTrustedMinter => remove_trusted_minter
        liquidateBorrow => liquidate_borrow
        mint => mint
        mintAndEnterMarket => mint_and_enter_market
        redeem => redeem
        repayBorrow => repay_borrow
        seize => seize
        getState => market_state
        getUnderlyingId => underlying_id
        getTokenId => token_id
        getOngoingIssuance => ongoing_issuance
        getMintedInitialSupply => minted_initial_supply
        getAccountBorrowSnapshot => account_borrow_snapshot
        getCash => cash
        getTotalBorrows => total_borrows
        getTotalReserves => total_reserves
        getStakingRewards => staking_rewards
        getHistoricalStakingRewards => historical_staking_rewards
        getRevenue => revenue
        getTotalSupply => total_supply
        getStakeFactor => stake_factor
        getAccrualTimestamp => accrual_timestamp
        getInitialExchangeRate => initial_exchange_rate
        getProtocolSeizeShare => protocol_seize_share
        getAccrualTimeThreshold => accrual_time_threshold
        claimStakingRewards => claim_staking_rewards
    )
}

multiversx_sc_wasm_adapter::async_callback! { money_market }
