// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           17
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    discount_rate_model
    (
        init => init
        upgrade => upgrade
        getAdmin => get_admin
        getPendingAdmin => get_pending_admin
        setPendingAdmin => set_pending_admin
        acceptAdmin => accept_admin
        isDiscountRateModel => is_discount_rate_model
        getDiscountsData => get_discounts_data
        getDiscountsCount => get_discounts_count
        getExchangeRate => get_exchange_rate
        getAccountDiscount => get_account_discount
        setDiscountData => set_discount_data
        removeDiscountData => remove_discount_data
        updateDiscountData => update_discount_data
        getController => controller
        getUshMoneyMarket => ush_money_market
        getUshTokenId => ush_token_id
        hasDiscountData => has_discount_data
        getDiscountsDataList => discounts_data_list
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
