// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           84
// Async Callback:                       1
// Total number of exported functions:  87

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    ush_money_market
    (
        init => init
        upgrade => upgrade
        issueHatomUSH => issue_hatom_ush
        setMarketRoles => set_market_roles
        getAdmin => get_admin
        getPendingAdmin => get_pending_admin
        setPendingAdmin => set_pending_admin
        acceptAdmin => accept_admin
        borrow => borrow
        isMoneyMarket => is_money_market
        isUshMarket => is_ush_market
        isActive => is_active
        isFinalized => is_finalized
        isHushIssued => is_hush_issued
        accrueInterest => accrue_interest
        tryAccrueInterest => try_accrue_interest
        addReserves => add_reserves
        ushToHush => ush_to_hush
        hushToUsh => hush_to_ush
        getMoneyMarketIdentifiers => get_money_market_identifiers
        getCurrentTotalBorrows => current_total_borrows
        getBaseTotalBorrows => get_base_total_borrows
        getCurrentTotalReserves => current_total_reserves
        getCurrentStakingRewards => get_current_staking_rewards
        getCurrentHistoricalStakingRewards => get_current_historical_staking_rewards
        getCurrentRevenue => get_current_revenue
        getLiquidity => get_liquidity
        getReserveFactor => get_reserve_factor
        getController => get_controller
        getCurrentAccountBorrowAmount => current_account_borrow_amount
        getReliableAccountBorrowAmount => reliable_account_borrow_amount
        getStoredAccountBorrowAmount => stored_account_borrow_amount
        getBaseAccountBorrowAmount => base_account_borrow_amount
        getAccountSnapshot => get_account_snapshot
        getReliableAccountSnapshot => get_reliable_account_snapshot
        getBorrowIndex => get_borrow_index
        getStoredExchangeRate => get_stored_exchange_rate
        getExchangeRate => get_exchange_rate
        getCloseFactor => get_close_factor
        getLiquidationIncentive => get_liquidation_incentive
        updateAccountDiscountRate => update_account_discount_rate
        activate => activate
        finalize => finalize
        setStakingContract => set_staking_contract
        setStakeFactor => set_stake_factor
        setCloseFactor => set_close_factor
        setLiquidationIncentive => set_liquidation_incentive
        setProtocolSeizeShare => set_protocol_seize_share
        setBorrowApr => set_borrow_apr
        setDiscountRateModel => set_discount_rate_model
        reduceReserves => reduce_reserves
        setAccrualTimeThreshold => set_accrual_time_threshold
        addTrustedMinter => add_trusted_minter
        removeTrustedMinter => remove_trusted_minter
        liquidateBorrow => liquidate_borrow
        mintAndEnterMarket => mint_and_enter_market
        onMarketChange => on_market_change
        redeem => redeem
        repayBorrow => repay_borrow
        seize => seize
        claimStakingRewards => claim_staking_rewards
        getState => state
        getUshMinter => ush_minter
        getUshId => ush_id
        getHushId => hush_id
        getOngoingIssuance => ongoing_issuance
        getAccountBorrowSnapshot => account_borrow_snapshot
        getAccountPrincipal => account_principal
        getTotalBorrows => total_borrows
        getEffectiveBorrows => effective_borrows
        getTotalPrincipal => total_principal
        getTotalReserves => total_reserves
        getStakingRewards => staking_rewards
        getHistoricalStakingRewards => historical_staking_rewards
        getRevenue => revenue
        getTotalSupply => total_supply
        eligibleAsCollateral => eligible_as_collateral
        getBorrowRate => borrow_rate
        getLastBorrowRateUpdate => last_borrow_rate_update
        getStakeFactor => stake_factor
        getAccrualTimestamp => accrual_timestamp
        getStakingSc => staking_sc
        getDiscountRateModel => discount_rate_model
        getProtocolSeizeShare => protocol_seize_share
        getAccrualTimeThreshold => accrual_time_threshold
        getMarketBorrowers => market_borrowers
    )
}

multiversx_sc_wasm_adapter::async_callback! { ush_money_market }
