// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    interest_rate_model
    (
        init => init
        upgrade => upgrade
        isInterestRateModel => is_interest_rate_model
        getUtilization => get_utilization
        getModelParameters => get_model_parameters
        getBorrowRate => get_borrow_rate
        getSupplyRate => get_supply_rate
        getRates => get_rates
        getBaseRate => base_rate
        getFirstSlope => first_slope
        getLastSlope => last_slope
        getOptimalUtilization => optimal_utilization
        getMaxBorrowRate => max_borrow_rate
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
