name: CI

on:
    push:
        branches:
            - main
            - devnet
            - develop
    pull_request:
        branches:
            - main
            - devnet
            - develop

permissions:
    checks: write
    contents: read
    pull-requests: write

jobs:
    contracts:
        name: Contracts
        uses: HatomProtocol/hatom-sc-actions/.github/workflows/contracts.yml@main
        with:
            rust-toolchain: nightly-2024-05-22
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
        deploy-keys: |
            ${{ secrets.ADMIN_MODULE_SSH_DEPLOY_PRIVATE_KEY }}
            ${{ secrets.USH_MINTER_SSH_DEPLOY_PRIVATE_KEY }}
